### ISSUE TITLE
function support in Nereids

### ISSUE THREAD

**Issue by morrySnow** [apache/doris#13623]
Currently, nereids bind function by some if-else code, and can not compute the correct signature and can not do argument type implicitly cast.

Subtasks for the issue:
- [x] a function registry that we can find a function by the name and arguments arity #12481
- [x] a signature search/compute framework #13764
- [x] migrate the scalar functions from legacy function set #13764
- [x] migrate the aggregate functions from legacy function set #15671 
- [x] migrate the window functions from legacy function set
- [x] migrate the table functions from legacy function set #15121
- [x] #16690

**Comment by morrySnow** [comment]
#12671
