### ISSUE TITLE
tuning TPC-H plan generated by Nereids

### ISSUE THREAD

**Issue by morrySnow** [apache/doris#13634]
- [x] remove unnecessary cast to String #13730 
- [x] remove unnecessary cast to Decimal #13745
- [x] add datev2 support #14263
