### ISSUE TITLE
[Roadmap] Support Struct+Map Type

### ISSUE THREAD

**Issue by xy720** [apache/doris#16547]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

## Struct + Map todo list

- [x] 语法支持 **(2.0)**
    - [x] 建表+desc语句
    - [x] StructLiteral
	- [x] MapLiteral
- [x] Insert **(2.0)**
    - [x] Map
	- [x] Struct
- [x] Select **(2.0)**
    - [x] Map
	- [x] Struct
- [ ] Delete **(2.0)**
    - [ ] Map
    - [ ] Struct
- [ ] 子类型支持 **(2.0)**
    - [ ] struct field 支持 scala type
	- [ ] struct field 支持 nullable
	- [ ] map key/value 支持 scala type
- [ ] Struct嵌套类型支持
	- [ ] Array 嵌套 Struct
	- [ ] Struct 嵌套 Struct
	- [ ] Struct 嵌套 Array
- [ ] Map嵌套类型支持
	- [ ] value 嵌套 Array
	- [ ] value 嵌套 Struct
	- [ ] value 嵌套 Map
- [ ] Cast **(2.0)**
    - [ ] Struct 隐式 Cast 函数
	- [ ] Map 隐式 Cast 函数
	- [ ] 显式 Struct CastTo Struct
	- [ ] 显式 Map CastTo Map
	- [ ] 显式 StructLiteral CastTo StructLiteral
	- [ ] 显式 MapLiteral CastTo MapLiteral
- [ ] 导入 **(2.0)**
- Struct
	- [x] Json格式
	- [ ] csv格式
	- [ ] parquet格式
	- [ ] orc格式
- Map
	- [ ] Json格式
	- [ ] csv格式
	- [ ] parquet格式
	- [ ] orc格式
- [ ] 导出
- Struct
	- [ ] select into outfile
	- [ ] export
- Map
	- [ ] select into outfile
	- [ ] export
- [ ] 函数
- Struct
	- [ ] struct(val1, val2, val3, ...)
	- [ ] named_struct(name1, val1, name2, val2, ...)
	- [ ] s.x
- Map
	- [ ] map(key1, val1, key2, val2, ...)
	- [ ] M[key]/element_at
	- [ ] size/cardinality(Map<K,V>)
	- [ ] map_keys(Map<K,V>)
	- [ ] map_values(Map<K,V>)
	- [ ] map_entries(Map<K,V>)
	- [ ] map_contains(Map<K,V> map, K key)
	- [ ] map_contains_key_like(Map<K,V> map, pattern)
	- [ ] explode(MAP<K,V> m)
	- [ ] map_concat(Map<K,V> map1, Map<K,V> map2, ...)
	- [ ] str_to_map(text[, delimiter1, delimiter2])
	- [ ] map_filter(MAP<K,V> m, func)
	- [ ] map_zip_with(MAP<K,V> map1, MAP<K,V> map2, func)
	- [ ] map_add(MAP<K,V> map1, MAP<K,V> map2, ...)
	- [ ] map_substract(MAP<K,V> map1, MAP<K,V> map2, ...)
	- [ ] map_update(MAP<K,V> map1, MAP<K,V> map2)
- [ ] Schema change
- Struct
	- [ ] 增减 struct 列
	- [ ] 修改 struct field 类型
	- [ ] 增减 struct field
- Map
	- [ ] 增减 map 列
	- [ ] 修改 map 类型
- [ ] 外部数据源支持
- Struct
	- [ ] hive
	- [ ] iceberg
- Map
	- [ ] hive
	- [ ] iceberg
- [ ] 新优化器支持
- [ ] 支持各个索引
- [ ] 支持unique key

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xiaokang** [comment]
+ support in new optimizer

**Comment by zhannngchen** [comment]
BTW, please consider supporting the unique table.

**Comment by xiaokang** [comment]
add: support index
