### ISSUE TITLE
[Enhancement] use unique id to identify column in schema completely

### ISSUE THREAD

**Issue by TangSiyang2001** [apache/doris#23617]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Currently we still use column name to identify a column in schema in some places, which reveals a lot of problems. 

### Solution

- [x] add column unique id in delete predicates #22442 #24549
- [x] flush column unique ids for table before 1.2 automatically. #23616 
- [x] add a `show` command to show reasons about tables which is not able to support light schema change #23616 
- [ ] forbid tables created with property `enable_light_schema_change = false;`#23620

**To be continue...**

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
