### ISSUE TITLE
[Draft] Doris Roadmap 2024

### ISSUE THREAD

**Issue by morningman** [apache/doris#30669]
[Roadmap 2023](https://github.com/apache/doris/issues/16392)
[Roadmap 2022](https://github.com/apache/doris/issues/7502)

## Separation of Storage and Computation

- Flexibility & Stateless
    - [ ] Stateless BE node
    - [ ] Stateless FE node
- Load Isolation
    - [ ] Mutlt cluster support 
    - [ ] Read & write isolation
- More storage support
  - [x] AWS S3
  - [x] Aliyun OSS 
  - [x] Tencent Cloud COS
  - [x] Huawei Cloud OBS
  - [ ] GCP
  - [ ] Azure
  - [ ] HDFS
- Performance
  - [x] Optimized cache policy
  - [ ] Optimization for cold data querying
- [x] Support data deletion
- SLA
  - [ ] Upgrade BE with no impact
  - [ ] Upgrade FE with no impact
- Reliability
  - [ ] Snapshot & Time travel
  - [ ] Enhanced backup & restore
- [ ] Data sharing

## [Async Materialized View](https://doris.apache.org/docs/dev/query-acceleration/async-materialized-view)

- Build materialized view
    - [x] Support full refresh
    - [x] Support partition level refresh
    - [x] Support building mv from olap table
    - [x] Support building mv from hive table
    - [ ] Support building mv from iceberg table
    - [ ] Support building mv from hudi table
    - [ ] Nested materialized view with DAG
    - [ ] Incremental building for external table with partition granularity
    - [ ] Support partition rollup
    - [ ] Support partition TTL
    - [ ] Support `REPLACE` operation
    - [ ] Support refresh materialized view by time range

- [Transparent Rewriting](https://doris.apache.org/docs/dev/query-acceleration/async-materialized-view/query-async-materialized-view)
    - [x] Support aggregation and rollup
    - [x] Support join
    - [ ] Query Partial rewriting
    - [ ] Rewriting supports nested materialized view

- Materialized view management
    - [ ] Materialized view recommendation

## Semi Structure Data Analysis

- Inverted Index
    - [x] Support [Inverted Index](https://doris.apache.org/docs/dev/data-table/index/inverted-index/)
    - [ ] Merging index files
    - [ ] Working with separation of storage and computation
    - [ ] Speed up the data loading with inverted index

- VARIANT data type
    - [ ] Support `VARIANT` data type
    - [ ] Working with inverted index

## Query Optimizer

- Basic framework
   - [ ] Fully supports DQL, DML and DDL
   - [ ] Optimized memeory consumption
   - [ ] Optimized apply order of RBO rules
   - [ ] Improved efficiency of Cascades enumeration
- Planning quality
   - Statistics
     - [ ] Support statistical for synced materialized views
     - [ ] Support partition level statistics collection
     - [ ] Supports histogram statistics collection
   - New distributed cost model
     - [ ] Optimized distributed cost model framework
     - [ ] Support runtime cost revaluation
     - [ ] Supports more accurate operator cost fitting models
   - Rules and enumerations
     - [ ] Expand RBO rules
     - [ ] Improve the quality of Cascades enumeration plan
     - [ ] Enhanced dphyper enumeration framework function, supports outer join enumeration and CDC
   - Enhance runtime filter adaptive capability
     - [ ] Adaptive runtime filter size
     - [ ] Adaptive runtime filter type
     - [ ] Adaptive runtime filter waiting time
   - [ ] Supports histogram-based data skew adaptive processing framework

## DataLake Analytics 

- Support more file format
    - [ ] RCFile
    - [ ] SequenceFile

- Support more lake format
    - [ ] Support Iceberg with ORC
    - [ ] Support Iceberg Equality Delete
    - [ ] Support more systable on Hudi
    - [ ] Support CDC scan on Hudi
    - [ ] Support more systable on Paimon

- Trino Connector compatibility
    - [ ] Trino Connector compatibility framework
    - [ ] Support Trino DeltaLake Connector
    - [ ] Support Trino Bigquery Connector
    - [ ] Support Trino Cassandra Connector

- Datalake write back
    - Hive
        - [ ] Support unpartitioned table
        - [ ] Support partitioned table
        - [ ] Support `INSERT OVERWRITE`
        - [ ] Support `INSERT`
    - Iceberg
        - [ ] Support unpartitioned table
        - [ ] Support partitioned table
        - [ ] Support update and delete
    - Hudi
    - Paimon

- Enhanced JDBC Catalog
    - [ ] Support DB2
    - [ ] Support sharded database
    - [ ] Support query concurrency

- Enhanced file analysis
    - [ ] Support insert into table value function

- Enhanced file cache
    - [ ] Support memeory-level file cache
    - [ ] Enhanced cache statistic and hits analysis

- Integrate with Apache Ranger
    - [x] Support Catalog/Database/Table/Resource/WorkloadGroup auth
    - [ ] Support row policy
    - [ ] Support data mask
    - [ ] Support column level privilege

- [SQL dialect support](https://doris.apache.org/docs/dev/lakehouse/sql-dialect)
	- [x] Presto/Trino
	- [ ] Spark
	- [ ] Hive
	- [ ] Clickhouse
	- [ ] Oracel

## Query Processing

- [ ] Support store precedure
- Support Spill to disk
    - [ ] Sort Operator
    - [ ] Aggregate Operator
    - [ ] Join Operator
- [ ] Working with shuffle service
- [ ] Stage by stage query processing

## Storage Engine

- Data Loading
    - [x] Support auto partiton when loading
    - [ ] Zero-ETL: Built-in data integration from OLTP CDC to Doris
    - [ ] Support transactional multi table `INSERT INTO`
    - [ ] Support `MERGE INTO`
- Data Modeling
    - [x] Auto incremental column
    - [ ] Support `CLUSTER BY`
    - [ ] Support KEY column in arbitrary order
- CCR(Cross cluster replication)
    - [ ] Support Master/Slave switch
    - [ ] Support cross region deployment
    - [ ] Work with separation of storage and computation
- [ ] Support data binlog
- [ ] Enhanced Z-order index
- [ ] Optimized high-concurrency point query

## Ecosystem & Tools

- Cluster Manager for Apache Doris
- [x] Doris StreamLoader tool        
- X2Doris
    - [x] Support Hive to Doris
    - [x] Support Doris to Doris
    - [x] Support Kudu to Doris
    - [x] Support StarRocks to Doris
    - [ ] Support Clickhouse to Doris
- BI tools compatibility
    - [x] Superset
    - [ ] Metabase
    - [ ] Navicat
    - [ ] Datagrip
    - [ ] Dbeaver
    - [ ] SmartBI
    - [ ] FineBI
- Data Integration
    - [ ] Kettle

**Comment by vinlee19** [comment]
Flink-connector-doris will use FlinkCDC to synchronize multiple tables or the entire database from MongoDB and DB2 to Doris.

**Comment by michael1991** [comment]
typo "Mutlt cluster support" => "Multi cluster support"

**Comment by ihadoop** [comment]
hi，i write a mtebase doris driver for the lastest metabase

**Comment by Hanchers** [comment]
Looking forward to version 2.1

**Comment by longzmkm** [comment]
> Looking forward to version 2.1

me too

**Comment by vonwind** [comment]
Walking with innovators

**Comment by stalary** [comment]
Can we support doris cdc to resolve multilayer data import?

**Comment by zhbdesign** [comment]
Support generating columns

**Comment by morningman** [comment]
> Currently, I have completed the development and testing of the JDBC catalog for Apache Druid. If possible, I would like to contribute this feature. PR:#27270

HI @vinlee19 , thanks for your contribution. I'm not sure if it is suitable for Druid to using JDBC as data connector? I'm concerning the performance issue. But indeed Trino is using JDBC connect Druid.
I will take a look at this feature, and could you please also provide test cases (eg. druid docker compose)?

**Comment by liugddx** [comment]
https://github.com/dbeaver/dbeaver/pull/22836

**Comment by liugddx** [comment]
https://github.com/langchain-ai/langchain/pull/17527

**Comment by cs3163077** [comment]
> Looking forward to version 2.1

me too

**Comment by dragonkid** [comment]
why there is no 'Support building mv from Paimon table'

**Comment by morningman** [comment]
> why there is no 'Support building mv from Paimon table'

It will be supported

**Comment by morningman** [comment]
> `BI tools compatibility` Can it be adapted to https://github.com/devlive-community/datacap?
Hi @qianmoQ,
I am not familiar with datacap, but you are very welcome to helping Doris adapt to it.
I saw the Doris is on the log wall, maybe you can post a blog on Doris website about how to connect to Doris using datacap?

**Comment by ShawshankLin** [comment]
Support transactional multi table DELETE INSERT for adapting aggregate tables in dbt's Incremental models

**Comment by JiangJamm** [comment]
Look forward to supporting DataGrip and kettle!

**Comment by shiliming** [comment]
binlog，binlog，binlog!

**Comment by mohuaiyuan** [comment]
Which version of Doris is preparing to support DB2？

**Comment by johnpyp** [comment]
On the "Index Overview" page in the docs, I see that Inverted Indexes have `Accelerates LIKE` marked as "COMING" - is that part of the 2024 roadmap? That would be amazing :)

**Comment by rudyricci** [comment]
HI,
The 2024 roadmap lacks support for AWS S3 via the IAM role, an activity that was marked in the 2023 roadmap. I think it is very important to avoid having hardcoded credentials for security reasons.
See https://github.com/apache/doris/issues/35928

**Comment by malthe** [comment]
According to this roadmap, inverted indexes are not yet "working with separation of storage and computation", but is there an issue tracking this?

**Comment by msridhar78** [comment]
Stateless FE feature looks interesting. What does Stateless FE mean? Storing no local states/contexts? Like session states, user authentication states? Another FE can takeover in between query execution? Can you please elaborate on what is planned for this at the high level?

**Comment by Ajax4jsf-ravaged** [comment]
> According to this roadmap, inverted indexes are not yet "working with separation of storage and computation", but is there an issue tracking this?





https://stackdev.space/questions/combining-an-apache-spark-cluster-with-various-databases
