### ISSUE TITLE
[Doris On Elasticsearch] Develop Roadmap

### ISSUE THREAD

**Issue by wuyunfeng** [apache/doris#3306]
Community users are very welcome to actively participate in the development!

- [ ]  **Move the Predicate-Processing from Doris BE to Doris FE** @wuyunfeng 

- [x]  **directly process the `CastExpr`**   @wuyunfeng 

- [ ]  **support function push-down，such as `a = b`**  

- [ ]  **add `QueryStringQuery` for analyzed field, gradually discard `es_query`**

- [ ]  **improve the performance under muti-table joins, provide more data/index statistic infomation**

- [ ]  **push down aggreate operator to Elasticsearch such as count/avg/sum etc under single index context**

- [ ] **add the ability for process `object` and `nested` type field**

- [x] **fetch index mapping and shard location divided into two/three phase**     @stalary 

    1. GET {index}/{type}/_mapping 

    2. GET _nodes/http

    3. GET {index}/_search_shards

- [x]  **add ability for processing wildcard and alias index** @wuyunfeng 

- [x] **support alter operation for ES table**       @HappenLee 

- [ ] **Extended sql such as load all table from Elasticsearch, get rid of creating table manually**

- [ ] **Add Debug mode for ES table** @wuyunfeng 

- [x] **When reading more column values such as above 20, switch from column reading to row reading** @wuyunfeng 

- [ ] **Support ES partition to meet the demand of auto-deleting some data out of data in ES** @blackfox1983

**Comment by wuyunfeng** [comment]
https://github.com/apache/incubator-doris/issues/3249

**Comment by blackfox1983** [comment]
简直就是业务线同学福音！！！！！
非常期待这些feature的上线。也希望有机会一起开发。

**Comment by stalary** [comment]
`index mapping和shard location的检测分成两个阶段`
这个我来搞下

**Comment by wuyunfeng** [comment]
@stalary OK

**Comment by imay** [comment]
> `index mapping和shard location的检测分成两个阶段`
> 这个我来搞下

@stalary 
You can create another issue to track it

**Comment by wuyunfeng** [comment]
https://github.com/apache/incubator-doris/issues/3327

**Comment by wuyunfeng** [comment]
https://github.com/apache/incubator-doris/pull/3351 for  `增加对CastExpr过滤条件的处理`

**Comment by stalary** [comment]
支持对Elasticsearch外表的alter操作这个我处理下

**Comment by wuyunfeng** [comment]
> 支持对Elasticsearch外表的alter操作这个我处理下

👌， cool

**Comment by wuyunfeng** [comment]
https://github.com/apache/incubator-doris/issues/3759

**Comment by ColinVon** [comment]
@wuyunfeng 
add ability for processing wildcard index ?

由于涉及中文字段的长度加工与计算（char_length, strleft与strright）的使用，近期将Doris升级到最新版本（2020-06-11 Git Clone），但造成了通配符指定index的Table无法查询，提示错误信息如下：

`
fetch es table [sometable] metadata failure: index[sometable-*] not found for the Elasticsearch Cluster'
`

旧版本中，这个功能是正常使用的，请问是重构后引入问题吗？有什么办法能支持使用通配么？

在此感谢Doris各位开发者的无私奉献 :)

**Comment by wuyunfeng** [comment]
@ColinVon 目前重构的部分还没有合入，此前的版本也是不支持sometable-*匹配的。因为一旦涉及到多个index，目前的分区拆分会有问题 。你提到的 `add ability for processing wildcard index ` 目前还没有做。

**Comment by blackfox1983** [comment]
- [ ] Support ES partition to meet the demand of auto-deleting some data out of data in ES

**Comment by wuyunfeng** [comment]
https://github.com/apache/incubator-doris/issues/3967

**Comment by wuyunfeng** [comment]
add ability for processing wildcard and alias index: https://github.com/apache/incubator-doris/pull/3968

**Comment by wuyunfeng** [comment]
https://github.com/apache/incubator-doris/pull/4055

**Comment by wuyunfeng** [comment]
@ColinVon 更新下Doris的代码，现在已经完全支持 sometable-* 了

**Comment by ColinVon** [comment]
> @ColinVon 更新下Doris的代码，现在已经完全支持 sometable-* 了，支持alias和wildcard两种
> 
> 参考下这个：#3968

非常感谢，我试试看

**Comment by wuyunfeng** [comment]
https://github.com/apache/incubator-doris/pull/4699  support alter operation for ES table

**Comment by LinhaoZhu** [comment]
> * Support ES partition to meet the demand of auto-deleting some data out of data in ES

@wuyunfeng @blackfox1983 Is there a tracking number for this issues?
