### ISSUE TITLE
[Roadmap] Support automatic table structure transformation and pseudo data generation

### ISSUE THREAD

**Issue by morningman** [apache/doris#7781]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Use case

Use Case:

1. Automate or guide users in converting table build statements from other databases to Doris table build statements.

2. Support generating pseudo data based on table structure for easy testing

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
