### ISSUE TITLE
[Enhancement] [Sequnece Column] sequence column can reuse the column already in table to reduce mem/storage cost

### ISSUE THREAD

**Issue by HappenLee** [apache/doris#7962]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

## Motivation
Implemented by adding a hidden column `__DORIS_SEQUENCE_COL__`, the type of the column is specified by the user while create the table, determines the specific value of the column on import, and replaces the REPLACE column with that value.

**In many scenarios, the user's table usually has its own time or sequence attributes. We should reuse this part of the column for sequential de duplication, rather than regenerating a hidden column to complete this task.**

### It can bring us the following benefits:

1. In some memory tight scenarios, more memory is available at the expense of query execution time. This is necessary in some scenarios

2. Reduce unnecessary storage space of `__DORIS_SEQUENCE_COL__`,

3. Speed up the compaction task and query

## Implementation

#TODO

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
