### ISSUE TITLE
[Enhancement] [GroupingSet] Optimization of query of grouping set

### ISSUE THREAD

**Issue by HappenLee** [apache/doris#7966]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

## Motivation
The grouping set query implemented by Doris is inferior to Kylin, Hive and other competitive products in terms of performance. The main reasons are as follows

1. There are many ineffective data duplication in the process of implementation, and many functions that should not be calculated are calculated, for example, **grouping functions should not be calculated as group by columns.*

2. **Aggregation push down is not implemented**, which will lead to a large amount of data duplication.

### What shoule we do

1. Aggregate and push down, such as `grouping set ((a), (b), (a, b))`,  should `aggregate (a,b) first`, and then duplicate the data of grouping set, which can reduce the generation of a large amount of duplicate data and greatly improve the query efficiency

2. Reduce unnecessary funcion compute in grouping set query.

### Solution

#TODO

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
